Work around Xrender bug -- some versions of Xrender.h use Xlib types without including <X11/Xlib.h>, causing
In file included from /usr/include/X11/extensions/Xrender.h:28,
                 from kdebase/workspace/plasma/plasma/plas
maapp.cpp:47:
/usr/include/X11/extensions/render.h:29: error: 'XID' does not name a type
/usr/include/X11/extensions/render.h:30: error: 'XID' does not name a type
/usr/include/X11/extensions/render.h:31: error: 'XID' does not name a type
/usr/include/X11/extensions/render.h:32: error: 'XID' does not name a type
In file included from /usr/src/ark/BUILD/kdebase/workspace/plasma/plasma/plas
maapp.cpp:47:
/usr/include/X11/extensions/Xrender.h:47: error: 'PictFormat' does not name a
 type
[...]


svn path=/trunk/KDE/kdebase/workspace/; revision=740048