Improve the config dialog: * Port Q3ListView to QTreeWidget * Better and friendlier layout of pages * Display some nice icons * Remove some not anymore needed hacks * Point to Wikipedia article about Regexp instead of to the Qt documentation, since this one is less technically
Notice: KRegExpEditor is disabled because it is atm unusable

=> Klipper does not anymore depend on K3* or Q3* classes :)
Unfortunately it does not compile without QT3SUPPORT lib. Any ideas?

...data.rel.ro._ZTV7Q3GList[vtable for Q3GList]+0xc): undefined reference to Q3GList::clear()...

svn path=/trunk/KDE/kdebase/workspace/; revision=727535